import os, re, json, subprocess
import numpy as np
from PIL import Image, ImageEnhance

ROOT = "/Users/josefigueroa/Desktop/adg-landing"
SRC = ROOT + "/public"
OUT = ROOT + "/public/assets/hq/"
os.makedirs(OUT, exist_ok=True)
ESR = "/tmp/esr/realesrgan-ncnn-vulkan"

# every image the site uses: project/investment images and galleries, the shovel, the dusk render
data = open(ROOT + "/src/data.ts").read()
paths = sorted(set(re.findall(r'"(/assets/images/website/[^"]+\.(?:jpg|jpeg|png))"', data)))
paths += ["/assets/images/website/closing-the-gap.jpg", "/assets/images/website/aura-living-render-4.jpg"]
paths = sorted(set(p for p in paths if not p.endswith(".png") and not re.search(r"figueroa|fernandez|villar", p)))


def grade(im):
    a = np.asarray(im).astype(np.float32)
    # gentle levels: clip 0.4% at each end per channel (cleans whites, deepens blacks without color casts)
    lo = np.percentile(a, 0.4, axis=(0, 1)); hi = np.percentile(a, 99.6, axis=(0, 1))
    lo = lo.min() * np.ones(3); hi = hi.max() * np.ones(3)      # same stretch on all channels: no hue shift
    a = np.clip((a - lo) / np.maximum(hi - lo, 1) * 255, 0, 255)
    im = Image.fromarray(a.astype(np.uint8))
    im = ImageEnhance.Contrast(im).enhance(1.04)
    # normalize saturation toward a shared target so photos and renders sit together
    hsv = np.asarray(im.convert("HSV")).astype(np.float32)
    s_mean = hsv[..., 1].mean()
    factor = float(np.clip(92.0 / max(s_mean, 1), 0.85, 1.12))
    im = ImageEnhance.Color(im).enhance(factor)
    # a touch of warmth
    a = np.asarray(im).astype(np.float32)
    a[..., 0] *= 1.012; a[..., 2] *= 0.988
    return Image.fromarray(np.clip(a, 0, 255).astype(np.uint8))


done = {}
for p in paths:
    src = SRC + p
    if not os.path.exists(src):
        print("missing", p); continue
    im = Image.open(src).convert("RGB")
    name = os.path.basename(p).replace(" ", "-")
    if im.width < 2000:
        tmp = "/tmp/esr/up_" + name + ".png"
        subprocess.run([ESR, "-i", src, "-o", tmp, "-n", "realesrgan-x4plus", "-m", "/tmp/esr/models"], check=True, capture_output=True, cwd="/tmp/esr")
        up = Image.open(tmp).convert("RGB")
        target_w = min(2400, im.width * 2)
        im = up.resize((target_w, round(up.height * target_w / up.width)), Image.LANCZOS)
        how = "upscaled"
    else:
        if im.width > 2400:
            im = im.resize((2400, round(im.height * 2400 / im.width)), Image.LANCZOS)
        how = "resized"
    im = grade(im)
    out = OUT + os.path.splitext(name)[0] + ".jpg"
    im.save(out, quality=84, optimize=True, progressive=True)
    done[p] = "/assets/hq/" + os.path.basename(out)
    print(f"{how:9s} {name:42s} -> {im.size} {os.path.getsize(out)//1024} KB")

open(ROOT + "/src/hq.ts", "w").write(
    "// Upscaled and color-graded versions of site images (generated by design-sources/upgrade_images.py)\n"
    "export const HQ: Record<string, string> = " + json.dumps(done, indent=2) + ";\n"
    "export const hq = (src: string) => HQ[src] ?? src;\n")
print("mapped", len(done))
